### ISSUE TITLE
Tests for `bind_databases`

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits#114]
Write tests before investigating TODO comment in function

- `  names(databases) <- sapply(databases, "[[", "dataset_id")`

- removing ... and have` databases = list(...)` as inputs only

**Comment by ehwenk** [comment]
The reason that line needs to change is the function was written to bind datasets that have specific dataset_id's - because it was for binding datasets being merged together into traits.build. Now it is about merging together datasets by name. But we're going to have to work out a way the same function can be used in both cases - 1) For processing traits.build where each incoming dataset is based on its dataset_id; 2) For binding together any traits.build databases - likely to be various "extracts" based on some column value.
