### ISSUE TITLE
summarise_trait_means fails for categorical traits

### ISSUE THREAD

**Issue by alexskeels** [traitecoevo/austraits#71]
Hi there,

Love the package, really great job team!

This is part bug report and part feature reuest... So when transforming the austraits data into wide format, we first have to summarise the cases where we have multiple observations of the same trait for a species, using summarise_trait_means(). The first line of this function is:

suppressWarnings(trait_data <- trait_data %>% dplyr::mutate(value = as.numeric(value),  replicates = as.numeric(replicates)))

This line turns all categorical traits into NA. This makes sense for the downstream stuff as you can't get a mean for character vectors anyway. however, I guess the expected outcome of this function is that it would return the modal value of these categorical traits. 

So the bug (if it is really a bug and not a feature) is that summarise_trait_means retruns NAs for non numeric traits.

The feature request is whether its possible to have this function or another function return a modal value for these traits? Or, is there another way to summarise the data to get it into a wide format while maintaining these traits? In other words, is there any way to get a wide table with a single value for each species for both numeric and categorical traits?

Thanks very much in advance for this, and again the R package and dataset are fantastic!

To reproduce:

austraits <- load_austraits(version = "3.0.2", path = "data/austraits")

proteaceae <- extract_taxa(austraits, family = "Proteaceae") # subset

data_wide_bound <- proteaceae$traits %>%
  summarise_trait_means() %>% 
  trait_pivot_wider() 

all(is.na(data_wide_bound $value$fire_response)) # TRUE

**Desktop (please complete the following information):**
 - OS: Windows 10
 - austraits Version 2.1.2
 - R Version 4.3.0

**Comment by fontikar** [comment]
Hey @alexskeels so lovely to hear from you - even if its via GitHub issue 😄 

That is really good suggestion and a use case I didn't even think about it, so thank you for bringing it to us!

Certainly returning NA is **less than ideal** for categorical traits. How to handle them is an interesting challenge... 🤔 

Unfortunately, I don't have the capacity to debug this now!  Current workaround is the use the `as_wide_table` function. I hope this is helpful!!!

```
data_wide <- as_wide_table(proteaceae)

data_wide |> 
  filter(trait_name == "fire_response")

# A tibble: 1,081 × 31
   dataset_id observation_id  trait_name    taxon_name  trait_value unit  value_type replicates date 
   <chr>      <chr>           <chr>         <chr>       <chr>       <chr> <fct>      <chr>      <chr>
 1 Cheal_2017 Cheal_2017_0205 fire_response Adenanthos… resprouts   NA    expert_me… NA         NA   
 2 Cheal_2017 Cheal_2017_0622 fire_response Banksia cr… resprouts   NA    expert_me… NA         NA   
 3 Cheal_2017 Cheal_2017_0623 fire_response Banksia in… resprouts   NA    expert_me… NA         NA   
 4 Cheal_2017 Cheal_2017_0624 fire_response Banksia ma… resprouts   NA    expert_me… NA         NA   
 5 Cheal_2017 Cheal_2017_0625 fire_response Banksia or… fire_killed NA    expert_me… NA         NA   
 6 Cheal_2017 Cheal_2017_0626 fire_response Banksia sa… fire_killed NA    expert_me… NA         NA   
 7 Cheal_2017 Cheal_2017_0627 fire_response Banksia se… resprouts   NA    expert_me… NA         NA   
 8 Cheal_2017 Cheal_2017_0628 fire_response Banksia sp… fire_killed NA    expert_me… NA         NA   
 9 Cheal_2017 Cheal_2017_1275 fire_response Conospermu… resprouts   NA    expert_me… NA         NA   
10 Cheal_2017 Cheal_2017_1276 fire_response Conospermu… resprouts   NA    expert_me… NA         NA   
# ℹ 1,071 more rows
# ℹ 22 more variables: collection_type <chr>, sample_age_class <chr>, sampling_strategy <chr>,
#   `latitude (deg)` <chr>, `longitude (deg)` <chr>, site_name <chr>, site <chr>,
#   context_name <chr>, context <chr>, methods <chr>, original_name <chr>,
#   dataset_description <chr>, source_primary_citation <chr>, source_secondary_citation <chr>,
#   taxonomicStatus <chr>, taxonDistribution <chr>, taxonRank <chr>, genus <chr>, family <chr>,
#   acceptedNameUsageID <chr>, scientificNameAuthorship <chr>, ccAttributionIRI <chr>
# ℹ Use `print(n = ...)` to see more rows
  ```

 I have added a test for this on the branch `categorical` for future me to address and below I am making some notes to myself...

Here I am subsetting categorical traits, and counting the number of observations for  taxon_name, trait_name, observation_id. If n > 1, these are the ones that will need to be "collapsed down". 
``` 
proteaceae$traits |> 
  dplyr::filter(is.na(unit)) |> 
  group_by(taxon_name, trait_name, observation_id) |> 
  summarise(n = n()) |> 
  filter(n > 1) |> 
  arrange(-n)

`summarise()` has grouped output by 'taxon_name', 'trait_name'. You can override using
the `.groups` argument.
# A tibble: 292 × 4
# Groups:   taxon_name, trait_name [292]
   taxon_name             trait_name        observation_id         n
   <chr>                  <chr>             <chr>              <int>
 1 Grevillea arenaria     flower_colour     RBGSYD_2014_2_3034     4
 2 Grevillea jephcottii   flower_colour     RBGSYD_2014_2_3050     4
 3 Grevillea juniperina   flower_colour     RBGSYD_2014_2_3053     4
 4 Grevillea macleayana   flower_colour     RBGSYD_2014_2_3060     4
 5 Grevillea nematophylla flower_colour     RBGSYD_2014_2_3064     4
 6 Grevillea shiressii    flower_colour     RBGSYD_2014_2_3077     4
 7 Grevillea willisii     flower_colour     RBGSYD_2014_2_3083     4
 8 Persoonia adenantha    plant_growth_form RBGSYD_2014_2_4654     4
 9 Persoonia conjuncta    plant_growth_form RBGSYD_2014_2_4661     4
10 Triunia youngiana      plant_growth_form RBGSYD_2014_2_6223     4
# ℹ 282 more rows
# ℹ Use `print(n = ...)` to see more rows
  ```
 Some traits like flower_colour have a lot of different values for the same taxon and I'm not sure how folks would feel if these are collapsed by taking the modal value...
 
 ```
 proteaceae$traits |> 
  dplyr::filter(taxon_name == "Grevillea arenaria" & trait_name == "flower_colour", observation_id == "RBGSYD_2014_2_3034") 
 ```

Maybe for categorical traits where there are multiple observations for the same observation id, we can concatenate trait_name with trait_value as the new 'value' so they are unique? 

The fix should pull out categorical traits first before this step:
`suppressWarnings(trait_data <- trait_data %>% dplyr::mutate(value = as.numeric(value), replicates = as.numeric(replicates)))`

since `as.numeric(value)` would turn character strings into NA.

**Comment by fontikar** [comment]
This function is due to a big revamp in 2025 following a plant traits workshop. At the moment we caution users to use `summarise_trait_means` and rather they opt for `as_wide_table`
