### ISSUE TITLE
reduced package dependencies for API launch

### ISSUE THREAD

**Issue by dcol2804** [traitecoevo/austraits#87]
Some of the packages required for the 5.0.0 release are not available in the current pre-made image used to launch the API.  

I would like a branch of the the austraits repository that imports the list of packages needed for in v 4.2.2 only. The packages not compatible with the current API image are forcats, ggplot2, ggpointdensity, ggbeeswarm, gridExtra, scales and viridis.

The alternative fix: In the long term it would be much better to create a new image with these packages pre-installed, although this would take longer. Chris is using this archive to source ubuntu versions of packages to build the image: https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+ . It now contains all of the packages listed above (a few of them weren't available earlier this year but have since been published) except for ggpointdensity. I could contact the cran2deb4ubuntu Build Team and ask if an ubuntu version of this package could be published but this may take time. 

A quick fix would be better because nectar needs us to relaunch the API by the 5th of December

**Comment by fontikar** [comment]
@dfalster since most of the non-compatible packages @dcol2804 listed here relate to the plotting functions for `austraits`, I wonder if you are happy for me to move these packages into `Suggests` in the DESCRIPTION file. This means they won't need to be installed by default, unless specified in install_github("traitecoevo/austraits", dependencies = c("Imports", "Suggests"))`. 

I recall we had that set up [previously](https://github.com/traitecoevo/austraits/commit/3375ce59c0a474fcf6e524da2e9d3d76fdae5015) but was[ recently reverted](https://github.com/traitecoevo/austraits/commit/181e695aecac577788f38076bed05a5e4cb3d32a#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c) with all the various upgrades for AusTraits. v5. 

I think this is a good idea to move `ggplot2, ggpointdensity, ggbeeswarm, gridExtra, scales and viridis` to `Suggests` again, since plot_trait_distribution_beeswarm has also been migrated to `traits.build`. 

Can do this on the develop branch and we can do a PR from there? Just need the green light!

**Comment by fontikar** [comment]
I'm on it! 🚀

**Comment by fontikar** [comment]
Clos
